# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Graffiti.create(title: "Bates Hendricks", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut pharetra sit. Eu augue ut lectus arcu bibendum. Lectus proin nibh nisl condimentum id.", lat: 12.678, lng: 67.324, imageId: "l45khkj34");
Graffiti.create(title: "Fountain Square Alley", description: "Venenatis cras sed felis eget velit aliquet sagittis id. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Feugiat nisl pretium fusce id velit ut tortor. Posuere urna nec tincidunt praesent.", lat: 39.7533371, lng: -86.1424427, imageId: "l45khkj34");
Graffiti.create(title: "Louisville Shotgun", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut pharetra sit.", lat: 38.1699135, lng: -85.813413, imageId: "l45khkj34");
Graffiti.create(title: "Corvallis Bando", description: "Eu augue ut lectus arcu bibendum. Lectus proin nibh nisl condimentum id. Venenatis cras sed felis eget velit aliquet sagittis id. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Feugiat nisl pretium fusce id velit ut tortor. Posuere urna nec tincidunt praesent. Mi bibendum neque egestas congue quisque.", lat: 44.5269257, lng: -123.2716277, imageId: "l45khkj34");
Graffiti.create(title: "Moab Alien Gas Station", description: "Venenatis cras sed felis eget velit aliquet sagittis id. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Feugiat nisl pretium fusce id velit ut tortor. Posuere urna nec tincidunt praesent.", lat: 38.943868, lng: -109.8516022, imageId: "l45khkj34");
Graffiti.create(title: "Wallowas", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec enim diam vulputate ut pharetra sit. Eu augue ut lectus arcu bibendum. Lectus proin nibh nisl condimentum id. Venenatis cras sed felis eget velit aliquet sagittis id. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Feugiat nisl pretium fusce id velit ut tortor. Posuere urna nec tincidunt praesent. Mi bibendum neque egestas congue quisque. Ullamcorper a lacus vestibulum sed arcu non. Pellentesque elit ullamcorper dignissim cras. Habitant morbi tristique senectus et netus.", lat: 44.8745792, lng: 117.1047189, imageId: "l45khkj34");